version: "2"

services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=onetwothree
      - MYSQL_DATABASE=todos
      - MYSQL_USER=root
    volumes:
      - ../data/mysql:/var/lib/mysql

  eventstore:
      image: eventstore/eventstore

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  todo_api_example:
    container_name: todo_api_example
    image: node:8.9.4
    command: tail -f /dev/null
    working_dir: /opt/app
    environment:
      - TODOS_DB_NAME=todos
      - TODOS_DB_HOST=db
      - TODOS_DB_USER=root
      - TODOS_DB_PASS=onetwothree
      - TODOS_ES_HOST=eventstore
    ports:
      - 8000:8000
    volumes:
      - ..:/opt/app